services:
  vector_system_tel:
    image: timberio/vector:0.48.0-debian
    restart: unless-stopped
    volumes:
      - ./vector_system_tel.yaml:/etc/vector/vector.yaml:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    environment:
      - NTT_HGW_ADDRESS
      - NTT_HGW_USERNAME
      - NTT_HGW_PASSWORD
      - O2_ORGNAME
      - O2_USER
      - O2_PASSWORD

  vector_system_sec:
    image: timberio/vector:0.48.0-debian
    restart: unless-stopped
    volumes:
      - ./vector_system_sec.yaml:/etc/vector/vector.yaml:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    environment:
      - NTT_HGW_ADDRESS
      - NTT_HGW_USERNAME
      - NTT_HGW_PASSWORD
      - O2_ORGNAME
      - O2_USER
      - O2_PASSWORD

  vector_system_inf:
    image: timberio/vector:0.48.0-debian
    restart: unless-stopped
    volumes:
      - ./vector_system_inf.yaml:/etc/vector/vector.yaml:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    environment:
      - NTT_HGW_ADDRESS
      - NTT_HGW_USERNAME
      - NTT_HGW_PASSWORD
      - O2_ORGNAME
      - O2_USER
      - O2_PASSWORD

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: ${O2_ROOT_USER}
      ZO_ROOT_USER_PASSWORD: ${O2_ROOT_PASS}
      ZO_LOCAL_MODE: "true"
      ZO_LOCAL_MODE_STORAGE: "disk"
      ZO_HTTP_PORT: "5080"
    ports:
      - "5080:5080"
    volumes:
      - ./data:/data
